apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-statefulset
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: postgresql-container
          image: postgresql:latest
          env:
            - name: DB_HOST
              value: 192.168.49.2
            - name: DB_PORT
              value: 5432
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgresql-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-credentials
                  key: password

